import React, { useEffect, useState } from 'react';
import Head from 'next/head';

import Link from 'next/link';

const FrontPage = () => {
  const [storageItem, setStorageItem] = useState('');

  useEffect(() => {
    // "localStorage" issue solved
    if (localStorage) {
      const isLoginTrue = JSON.parse(localStorage.getItem('userLogin'));
      console.log('isLoginTrue', isLoginTrue);
      setStorageItem(isLoginTrue);
    }
  }, []);

  const userNotLogin = () => (
    <>
      <h2>It seem's like you are not login</h2>
      <h3>
        If you have an account, then please{' '}
        <Link href="/login">
          <a style={{ color: '#551a8b', textDecoration: 'underline' }}>Login</a>
        </Link>
      </h3>
      <h3>
        Don't have an account, then please do{' '}
        <Link href="/register">
          <a style={{ color: '#551a8b', textDecoration: 'underline' }}>
            Register
          </a>
        </Link>
      </h3>
    </>
  );
  return (
    <>
      <Head>
        <title>Front Welcome Page Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ marginTop: '100px' }}>
        {storageItem && storageItem.userLogin ? (
          <h2>Welcome Back User - {storageItem?.userEmail}</h2>
        ) : (
          <>{userNotLogin()}</>
        )}
      </div>
    </>
  );
};

export default FrontPage;
