import Head from 'next/head';
import FrontPage from './frontPage';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="container text-center">
      <Head>
        <title>login-register-jwt-Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className="">
          <FrontPage />
        </div>
      </main>
    </div>
  );
}
